apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-deployment
spec:
  selector:
    matchLabels:
      app: blazor
  replicas: 1
  template:
    metadata:
      labels:
        app: blazor
    spec:
      containers:
      - name: blazor
        image: __ACRFullImageName__
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blazor
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: blazor