name: Trigger auto deployment for AKS demo
on:
    push:
      branches: 
        [ main ]
      paths:
        - '**'
        - '.github/workflows/deploy-aks-package.yml'

    workflow_dispatch: {}
env:
    VERSION: v1
    ACR_RESOURCE_GROUP: red-aks-demo-rg
    AZURE_CONTAINER_REGISTRY: myaksrepo
    CLUSTER_NAME: myAKSCluster
    CLUSTER_RESOURCE_GROUP: red-aks-demo-rg
    CONTAINER_NAME: blazor-client
    NAMESPACE_NAME: aks-dev-ns
    TODO_BACKEND_SERVICE_NAME: todo-api-backend
    DEPLOYMENT_MANIFEST_PATH: |
        ./azure-aks-deployment.yaml
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: get todo backend api endpoint
              uses: azure/CLI@v1
              with:
                inlineScript: |
                  TODO_BACKEND_ENDPOINT=$(az aks command invoke -n ${{ env.CLUSTER_NAME }} -g ${{ env.CLUSTER_RESOURCE_GROUP }} -c 'kubectl describe services ${{ env.TODO_BACKEND_SERVICE_NAME }} --namespace ${{ env.NAMESPACE_NAME }}' | awk -F: '/^Endpoints/{print$2":"$3}' | xargs echo)
                  echo TODO_BACKEND_ENDPOINT=$TODO_BACKEND_ENDPOINT >> $GITHUB_ENV
            - name: Replace AppSettings variables
              uses: microsoft/variable-substitution@v1 
              with:
                  files: 'wwwroot/appsettings.json'
              env:
                message: This is from dev
                TodoApiBaseUrl: http://${{ env.TODO_BACKEND_ENDPOINT }}/
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ env.VERSION }}.${{ github.run_number }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./Dockerfile ./
            
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3

            - name: Find and Replace - Using Secrets
              run: find *.yaml -type f -exec sed -i ''s%__ACRFullImageName__%${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}.${{ github.run_number }}%g'' {} \;
            - name: Bash - Show XML Contents
              run: cat ${{ env.DEPLOYMENT_MANIFEST_PATH }}

            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            - uses: Azure/k8s-deploy@v4
              name: Deploys application
              with:
                action: deploy
                images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}.${{ github.run_number }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
                namespace: ${{ env.NAMESPACE_NAME }}
