name: Trigger auto deployment for red-scus-blazorclient-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/deploy-package.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Replace AppSettings variables
        uses: microsoft/variable-substitution@v1 
        with:
            files: 'appsettings.json'
        env:
            message: This is from dev
            TodoApiBaseUrl: https://red-scus-demo-aca.icymoss-1ea051d6.southcentralus.azurecontainerapps.io/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: redscusmyrepoacr.azurecr.io
          username: ${{ secrets.REDSCUSBLAZORCLIENTACA_REGISTRY_USERNAME }}
          password: ${{ secrets.REDSCUSBLAZORCLIENTACA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: redscusmyrepoacr.azurecr.io/red-scus-blazorclient-aca:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REDSCUSBLAZORCLIENTACA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n red-scus-blazorclient-aca -g red-scus-fun-with-containers-rg --server redscusmyrepoacr.azurecr.io --username  ${{ secrets.REDSCUSBLAZORCLIENTACA_REGISTRY_USERNAME }} --password ${{ secrets.REDSCUSBLAZORCLIENTACA_REGISTRY_PASSWORD }}
            az containerapp update -n red-scus-blazorclient-aca -g red-scus-fun-with-containers-rg --image redscusmyrepoacr.azurecr.io/red-scus-blazorclient-aca:${{ github.sha }} --replace-env-vars message='This is just a test' bar=foobar
